name: 'build'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build the app
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32
        path: ./
